const questions = {
  Maths: [
    { q: "What is the value of (a+b)^2?", options: ["a^2+b^2", "a^2+2ab+b^2", "a^2-ab+b^2"], answer: "a^2+2ab+b^2" },
    { q: "The sum of angles of a triangle is?", options: ["90°", "180°", "360°"], answer: "180°" },
    { q: "The sum of angles of a triangle is?", options: ["90°", "180°", "360°"], answer: "180°" },
    { q: "Value of sin 90°?", options: ["0", "1", "√3/2"], answer: "1" },
    { q: "Area of a circle with radius r?", options: ["πr", "πr²", "2πr"], answer: "πr²" },
    { q: "Roots of x²-5x+6=0?", options: ["2,3", "1,6", "3,6"], answer: "2,3" },
    { q: "Value of cos 0°?", options: ["0", "1", "∞"], answer: "1" },
    { q: "Circumference of circle?", options: ["πr²", "2πr", "πd"], answer: "2πr" },
    { q: "Median divides data into?", options: ["Two equal parts", "Four equal parts", "Three equal parts"], answer: "Two equal parts" },
    { q: "Probability of getting head in coin toss?", options: ["0.25", "0.5", "1"], answer: "0.5" },
    { q: "Surface area of sphere?", options: ["4πr²", "2πr²", "πr²"], answer: "4πr²" },
    { q: "Value of tan 45°?", options: ["0", "1", "√3"], answer: "1" },
  ],
  Science: [
    { q: "Which gas is released during photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Oxygen" },
    { q: "What is the SI unit of force?", options: ["Newton", "Joule", "Pascal"], answer: "Newton" }
    { q: "Which gas is released during photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Oxygen" },
  { q: "What is the SI unit of force?", options: ["Newton", "Joule", "Pascal"], answer: "Newton" },
  { q: "Which organelle is called the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome"], answer: "Mitochondria" },
  { q: "Which acid is present in lemon?", options: ["Acetic acid", "Citric acid", "Lactic acid"], answer: "Citric acid" },
  { q: "Which metal is liquid at room temperature?", options: ["Mercury", "Iron", "Aluminium"], answer: "Mercury" },
  { q: "Which vitamin is produced in the skin by sunlight?", options: ["Vitamin A", "Vitamin D", "Vitamin C"], answer: "Vitamin D" },
  { q: "Which gas is used in the preparation of soda water?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Carbon dioxide" },
  { q: "Which part of the plant conducts food?", options: ["Xylem", "Phloem", "Root"], answer: "Phloem" },
  { q: "Which lens is used to correct myopia?", options: ["Convex lens", "Concave lens", "Cylindrical lens"], answer: "Concave lens" },
  { q: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Venus"], answer: "Mars" },
  { q: "Which gas is responsible for global warming?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Carbon dioxide" },
  { q: "Which blood cells fight infections?", options: ["RBC", "WBC", "Platelets"], answer: "WBC" },
  { q: "Which device converts chemical energy into electrical energy?", options: ["Battery", "Generator", "Transformer"], answer: "Battery" },
  { q: "Which mirror is used in vehicles as rear-view mirror?", options: ["Concave", "Convex", "Plane"], answer: "Convex" },
  { q: "Which gas is used in balloons?", options: ["Hydrogen", "Helium", "Oxygen"], answer: "Helium" },
  { q: "Which part of the human body produces insulin?", options: ["Liver", "Pancreas", "Kidney"], answer: "Pancreas" },
  { q: "Which metal is used in making electrical wires?", options: ["Copper", "Iron", "Silver"], answer: "Copper" },
  { q: "Which organ purifies blood in humans?", options: ["Heart", "Kidney", "Lungs"], answer: "Kidney" },
  { q: "Which gas is used in fire extinguishers?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Carbon dioxide" },
  { q: "Which part of the eye controls the amount of light?", options: ["Retina", "Iris", "Lens"], answer: "Iris" },
  { q: "Which process converts water into vapour?", options: ["Condensation", "Evaporation", "Sublimation"], answer: "Evaporation" },
  { q: "Which part of the plant absorbs water?", options: ["Stem", "Root", "Leaf"], answer: "Root" },
  { q: "Which gas is essential for respiration?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Oxygen" },
  { q: "Which energy is obtained from flowing water?", options: ["Solar energy", "Hydroelectric energy", "Wind energy"], answer: "Hydroelectric energy" },
  { q: "Which part of the cell contains genetic material?", options: ["Nucleus", "Cytoplasm", "Mitochondria"], answer: "Nucleus" },
  { q: "Which organ helps in pumping blood?", options: ["Lungs", "Heart", "Kidney"], answer: "Heart" },
  { q: "Which gas is used in welding?", options: ["Oxygen", "Acetylene", "Nitrogen"], answer: "Acetylene" },
  { q: "Which metal is used in thermometers?", options: ["Mercury", "Copper", "Aluminium"], answer: "Mercury" },
  { q: "Which part of the digestive system absorbs nutrients?", options: ["Stomach", "Small intestine", "Large intestine"], answer: "Small intestine" },
  { q: "Which natural satellite revolves around Earth?", options: ["Moon", "Mars", "Venus"], answer: "Moon" },
  { q: "Which gas is used in fluorescent lamps?", options: ["Argon", "Oxygen", "Nitrogen"], answer: "Argon" },
  { q: "Which part of the plant makes food?", options: ["Root", "Leaf", "Stem"], answer: "Leaf" },
  { q: "Which organ stores bile?", options: ["Gall bladder", "Liver", "Pancreas"], answer: "Gall bladder" },
  { q: "Which energy is obtained from the Sun?", options: ["Solar energy", "Wind energy", "Hydroelectric energy"], answer: "Solar energy" },
  { q: "Which gas is used in respiration?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Oxygen" },
  { q: "Which organ helps in breathing?", options: ["Heart", "Lungs", "Kidney"], answer: "Lungs" },
  { q: "Which part of the ear helps in balance?", options: ["Cochlea", "Semicircular canals", "Eardrum"], answer: "Semicircular canals" },
  { q: "Which gas is used in photosynthesis?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Carbon dioxide" },
  { q: "Which organ removes waste from blood?", options: ["Kidney", "Liver", "Heart"], answer: "Kidney" },
  { q: "Which part of the plant transports water?", options: ["Xylem", "Phloem", "Root"], answer: "Xylem" },
  { q: "Which gas is used in respiration?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Oxygen" },
  { q: "Which organ produces digestive enzymes?", options: ["Pancreas", "Kidney", "Heart"], answer: "Pancreas" },
  { q: "Which part of the cell controls activities?", options: ["Nucleus", "Cytoplasm", "Mitochondria"], answer: "Nucleus" },
  { q: "Which gas is used in making bread rise?", options: ["Carbon dioxide", "Oxygen", "Nitrogen"], answer: "Carbon dioxide" },
  { q: "Which organ helps in circulation of blood?", options: ["Heart", "Lungs", "Kidney"], answer: "Heart" },
  { q: "Which part of the plant anchors it?", options: ["Root", "Stem", "Leaf"], answer: "Root" },
  { q: "Which gas is used in respiration?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Oxygen" },
  { q: "Which organ helps in filtering blood?", options: ["Kidney", "Liver", "Heart"], answer: "Kidney" },
  { q: "Which part of the cell is called the brain?", options: ["Nucleus", "Mitochondria", "Ribosome"], answer: "Nucleus" },
  { q: "Which gas is used in respiration?", options: ["Oxygen", "Carbon dioxide", "Nitrogen"], answer: "Oxygen" }
  ],
  SocialScience: [
    { q: "Who wrote the book 'Discovery of India'?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "B.R. Ambedkar"], answer: "Jawaharlal Nehru" },
    { q: "Which is the longest river in India?", options: ["Ganga", "Yamuna", "Brahmaputra"], answer: "Ganga" }
    { q: "Who wrote 'Discovery of India'?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "B.R. Ambedkar"], answer: "Jawaharlal Nehru" },
  { q: "Which is the longest river in India?", options: ["Ganga", "Yamuna", "Brahmaputra"], answer: "Ganga" },
  { q: "Who was the first Governor-General of independent India?", options: ["Lord Mountbatten", "C. Rajagopalachari", "Dr. Rajendra Prasad"], answer: "Lord Mountbatten" },
  { q: "Which year did India gain independence?", options: ["1945", "1947", "1950"], answer: "1947" },
  { q: "Which is the largest state of India by area?", options: ["Madhya Pradesh", "Rajasthan", "Uttar Pradesh"], answer: "Rajasthan" },
  { q: "Who is known as the Father of the Indian Constitution?", options: ["Mahatma Gandhi", "B.R. Ambedkar", "Jawaharlal Nehru"], answer: "B.R. Ambedkar" },
  { q: "Which movement was launched by Mahatma Gandhi in 1942?", options: ["Non-Cooperation", "Quit India", "Civil Disobedience"], answer: "Quit India" },
  { q: "Which is the capital of India?", options: ["Mumbai", "New Delhi", "Kolkata"], answer: "New Delhi" },
  { q: "Which is the highest mountain peak in India?", options: ["Kanchenjunga", "Mount Everest", "Nanda Devi"], answer: "Kanchenjunga" },
  { q: "Which Indian leader gave the slogan 'Do or Die'?", options: ["Subhash Chandra Bose", "Mahatma Gandhi", "Bhagat Singh"], answer: "Mahatma Gandhi" },
  { q: "Which state is known as the 'Land of Five Rivers'?", options: ["Punjab", "Haryana", "Uttar Pradesh"], answer: "Punjab" },
  { q: "Which is the national animal of India?", options: ["Lion", "Tiger", "Elephant"], answer: "Tiger" },
  { q: "Which is the national bird of India?", options: ["Peacock", "Sparrow", "Parrot"], answer: "Peacock" },
  { q: "Which is the national flower of India?", options: ["Rose", "Lotus", "Sunflower"], answer: "Lotus" },
  { q: "Which is the national game of India?", options: ["Cricket", "Hockey", "Kabaddi"], answer: "Hockey" },
  { q: "Which is the currency of India?", options: ["Dollar", "Rupee", "Pound"], answer: "Rupee" },
  { q: "Which is the largest democracy in the world?", options: ["USA", "India", "UK"], answer: "India" },
  { q: "Which river is called the 'Sorrow of Bihar'?", options: ["Kosi", "Ganga", "Yamuna"], answer: "Kosi" },
  { q: "Which state is famous for tea plantations?", options: ["Assam", "Kerala", "Punjab"], answer: "Assam" },
  { q: "Which Indian leader gave the slogan 'Jai Jawan Jai Kisan'?", options: ["Jawaharlal Nehru", "Lal Bahadur Shastri", "Indira Gandhi"], answer: "Lal Bahadur Shastri" },
  { q: "Which is the southernmost point of India?", options: ["Indira Point", "Kanyakumari", "Lakshadweep"], answer: "Indira Point" },
  { q: "Which state is known as the 'Spice Garden of India'?", options: ["Kerala", "Tamil Nadu", "Goa"], answer: "Kerala" },
  { q: "Which Indian leader formed the INA?", options: ["Mahatma Gandhi", "Subhash Chandra Bose", "Jawaharlal Nehru"], answer: "Subhash Chandra Bose" },
  { q: "Which is the smallest state of India by area?", options: ["Goa", "Sikkim", "Tripura"], answer: "Goa" },
  { q: "Which is the largest desert in India?", options: ["Thar Desert", "Rann of Kutch", "Cholistan"], answer: "Thar Desert" },
  { q: "Which state is known as the 'Fruit Bowl of India'?", options: ["Himachal Pradesh", "Uttarakhand", "Jammu & Kashmir"], answer: "Himachal Pradesh" },
  { q: "Which Indian leader gave the slogan 'Inquilab Zindabad'?", options: ["Bhagat Singh", "Mahatma Gandhi", "Subhash Chandra Bose"], answer: "Bhagat Singh" },
  { q: "Which is the largest river basin in India?", options: ["Ganga Basin", "Godavari Basin", "Krishna Basin"], answer: "Ganga Basin" },
  { q: "Which state is known as the 'Rice Bowl of India'?", options: ["Andhra Pradesh", "Punjab", "West Bengal"], answer: "Andhra Pradesh" },
  { q: "Which Indian leader gave the slogan 'Swaraj is my birthright'?", options: ["Bal Gangadhar Tilak", "Mahatma Gandhi", "Jawaharlal Nehru"], answer: "Bal Gangadhar Tilak" },
  { q: "Which is the largest plateau in India?", options: ["Deccan Plateau", "Chotanagpur Plateau", "Malwa Plateau"], answer: "Deccan Plateau" },
  { q: "Which state is known as the 'Silicon Valley of India'?", options: ["Karnataka", "Maharashtra", "Tamil Nadu"], answer: "Karnataka" },
  { q: "Which Indian leader gave the slogan 'Give me blood and I will give you freedom'?", options: ["Subhash Chandra Bose", "Mahatma Gandhi", "Bhagat Singh"], answer: "Subhash Chandra Bose" },
  { q: "Which is the largest dam in India?", options: ["Bhakra Nangal", "Sardar Sarovar", "Hirakud"], answer: "Bhakra Nangal" },
  { q: "Which state is known as the 'Land of Rising Sun'?", options: ["Arunachal Pradesh", "Assam", "Nagaland"], answer: "Arunachal Pradesh" },
  { q: "Which Indian leader gave the slogan 'Dilli Chalo'?", options: ["Subhash Chandra Bose", "Mahatma Gandhi", "Jawaharlal Nehru"], answer: "Subhash Chandra Bose" },
  { q: "Which is the largest lake in India?", options: ["Chilika Lake", "Vembanad Lake", "Dal Lake"], answer: "Vembanad Lake" },
  { q: "Which state is known as the 'Land of Forests'?", options: ["Madhya Pradesh", "Jharkhand", "Chhattisgarh"], answer: "Madhya Pradesh" },
  { q: "Which Indian leader gave the slogan 'Aram Haram Hai'?", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhash Chandra Bose"], answer: "Jawaharlal Nehru" },
  { q: "Which is the largest port in India?", options: ["Mumbai Port", "Kolkata Port", "Chennai Port"], answer: "Mumbai Port" },
  { q: "Which state is known as the 'Land of Gods'?", options: ["Uttarakhand", "Himachal Pradesh", "Kerala"], answer: "Uttarakhand" },
  { q: "Which Indian leader gave the slogan 'Sarfaroshi ki Tamanna'?", options: ["Ram Prasad Bismil", "Bhagat Singh", "Mahatma Gandhi"], answer: "Ram Prasad Bismil" },
  { q: "Which is the largest island in India?", options: ["Majuli", "Andaman", "Lakshadweep"], answer: "Andaman" },
  { q: "Which state is known as the 'Land of Festivals'?", options: ["Nagaland", "Manipur", "Assam"], answer: "Nagaland" },
  { q: "Which Indian leader gave the slogan 'Vande Mataram'?", options: ["Bankim Chandra Chatterjee", "Mahatma Gandhi", "Jawaharlal Nehru"], answer: "Bankim Chandra Chatterjee" },
  { q: "Which is the largest delta in India?", options: ["Sundarbans", "Godavari Delta", "Krishna Delta"], answer: "Sundarbans" },
  { q: "Which state is known as the 'Land of Palaces'?", options: ["Rajasthan", "Madhya Pradesh", "Gujarat"], answer: "Rajasthan" },
  ]
  English: [
    { q: "Identify the verb in: 'She runs fast.'", options: ["She", "runs", "fast"], answer: "runs" },
    { q: "Synonym of 'Happy'?", options: ["Sad", "Joyful", "Angry"], answer: "Joyful" }
    English: [
  { q: "Identify the verb in: 'She runs fast.'", options: ["She", "runs", "fast"], answer: "runs" },
  { q: "Synonym of 'Happy'?", options: ["Sad", "Joyful", "Angry"], answer: "Joyful" },
  { q: "Antonym of 'Brave'?", options: ["Cowardly", "Strong", "Bold"], answer: "Cowardly" },
  { q: "Choose the correct article: '___ apple a day keeps the doctor away.'", options: ["A", "An", "The"], answer: "An" },
  { q: "Past tense of 'Go'?", options: ["Gone", "Went", "Going"], answer: "Went" },
  { q: "Plural of 'Child'?", options: ["Childs", "Children", "Childes"], answer: "Children" },
  { q: "Which is a pronoun?", options: ["Book", "He", "Run"], answer: "He" },
  { q: "Which is an adjective in: 'The tall boy is running.'?", options: ["Tall", "Boy", "Running"], answer: "Tall" },
  { q: "Opposite of 'Hot'?", options: ["Cold", "Warm", "Cool"], answer: "Cold" },
  { q: "Which is a conjunction?", options: ["And", "Run", "Book"], answer: "And" },
  { q: "Which is a preposition in: 'The cat is under the table.'?", options: ["Cat", "Under", "Table"], answer: "Under" },
  { q: "Which is a noun in: 'The sun shines.'?", options: ["Sun", "Shines", "The"], answer: "Sun" },
  { q: "Past tense of 'Eat'?", options: ["Eaten", "Ate", "Eating"], answer: "Ate" },
  { q: "Which is a synonym of 'Big'?", options: ["Small", "Large", "Tiny"], answer: "Large" },
  { q: "Antonym of 'Fast'?", options: ["Quick", "Slow", "Rapid"], answer: "Slow" },
  { q: "Which is an adverb in: 'He speaks loudly.'?", options: ["Speaks", "He", "Loudly"], answer: "Loudly" },
  { q: "Which is a pronoun in: 'They are playing.'?", options: ["They", "Playing", "Are"], answer: "They" },
  { q: "Which is a verb in: 'Birds fly.'?", options: ["Birds", "Fly", "The"], answer: "Fly" },
  { q: "Plural of 'Mouse'?", options: ["Mouses", "Mice", "Mousees"], answer: "Mice" },
  { q: "Opposite of 'Light'?", options: ["Dark", "Bright", "Shiny"], answer: "Dark" },
  { q: "Which is a synonym of 'Begin'?", options: ["End", "Start", "Finish"], answer: "Start" },
  { q: "Antonym of 'Rich'?", options: ["Poor", "Wealthy", "Loaded"], answer: "Poor" },
  { q: "Which is a verb in: 'She sings well.'?", options: ["She", "Sings", "Well"], answer: "Sings" },
  { q: "Which is an adjective in: 'The red car is fast.'?", options: ["Red", "Car", "Fast"], answer: "Red" },
  { q: "Which is a preposition in: 'The book is on the table.'?", options: ["Book", "On", "Table"], answer: "On" },
  { q: "Past tense of 'Write'?", options: ["Written", "Wrote", "Writing"], answer: "Wrote" },
  { q: "Plural of 'Foot'?", options: ["Foots", "Feet", "Footes"], answer: "Feet" },
  { q: "Opposite of 'Young'?", options: ["Old", "New", "Fresh"], answer: "Old" },
  { q: "Synonym of 'Quick'?", options: ["Fast", "Slow", "Lazy"], answer: "Fast" },
  { q: "Antonym of 'Love'?", options: ["Hate", "Like", "Care"], answer: "Hate" },
  { q: "Which is a pronoun in: 'We are friends.'?", options: ["We", "Friends", "Are"], answer: "We" },
  { q: "Which is a verb in: 'The dog barked.'?", options: ["Dog", "Barked", "The"], answer: "Barked" },
  { q: "Plural of 'Tooth'?", options: ["Tooths", "Teeth", "Toothes"], answer: "Teeth" },
  { q: "Opposite of 'Day'?", options: ["Night", "Morning", "Evening"], answer: "Night" },
  { q: "Synonym of 'Beautiful'?", options: ["Ugly", "Pretty", "Bad"], answer: "Pretty" },
  { q: "Antonym of 'Strong'?", options: ["Weak", "Powerful", "Tough"], answer: "Weak" },
  { q: "Which is an adverb in: 'He runs quickly.'?", options: ["Runs", "Quickly", "He"], answer: "Quickly" },
  { q: "Which is a pronoun in: 'She is my friend.'?", options: ["She", "Friend", "My"], answer: "She" },
  { q: "Past tense of 'See'?", options: ["Saw", "Seen", "Seeing"], answer: "Saw" },
  { q: "Plural of 'Man'?", options: ["Mans", "Men", "Manes"], answer: "Men" },
  { q: "Opposite of 'Cold'?", options: ["Hot", "Cool", "Warm"], answer: "Hot" },
  { q: "Synonym of 'End'?", options: ["Finish", "Start", "Begin"], answer: "Finish" },
  { q: "Antonym of 'Tall'?", options: ["Short", "Big", "Small"], answer: "Short" },
  { q: "Which is a verb in: 'The baby cried.'?", options: ["Baby", "Cried", "The"], answer: "Cried" },
  { q: "Which is an adjective in: 'The blue sky is clear.'?", options: ["Blue", "Sky", "Clear"], answer: "Blue" },
  { q: "Which is a preposition in: 'The ball is under the chair.'?", options: ["Ball", "Under", "Chair"], answer: "Under" },
  { q: "Past tense of 'Speak'?", options: ["Spoke", "Speaking", "Spoken"], answer: "Spoke" },
  { q: "Plural of 'Woman'?", options: ["Womans", "Women", "Womanses"], answer: "Women" },
  { q: "Opposite of 'Happy'?", options: ["Sad", "Joyful", "Excited"], answer: "Sad" },
  { q: "Synonym of 'Angry'?", options: ["Mad", "Calm", "Peaceful"], answer: "Mad" },
  { q: "Antonym of 'Clean'?", options: ["Dirty", "Neat", "Clear"], answer: "Dirty" }
  ],
  Hindi: [
    { q: "‘भारत का संविधान’ किसने लिखा?", options: ["महात्मा गांधी", "डॉ. भीमराव अंबेडकर", "जवाहरलाल नेहरू"], answer: "डॉ. भीमराव अंबेडकर" },
    { q: "‘गोदान’ उपन्यास के लेखक कौन हैं?", options: ["मुंशी प्रेमचंद", "रामधारी सिंह दिनकर", "सूरदास"], answer: "मुंशी प्रेमचंद" },
    Hindi: [
  { q: "‘भारत का संविधान’ किसने लिखा?", options: ["महात्मा गांधी", "डॉ. भीमराव अंबेडकर", "जवाहरलाल नेहरू"], answer: "डॉ. भीमराव अंबेडकर" },
  { q: "‘गोदान’ उपन्यास के लेखक कौन हैं?", options: ["मुंशी प्रेमचंद", "रामधारी सिंह दिनकर", "सूरदास"], answer: "मुंशी प्रेमचंद" },
  { q: "‘रामचरितमानस’ किसने लिखा?", options: ["तुलसीदास", "कबीर", "सूरदास"], answer: "तुलसीदास" },
  { q: "‘मधुशाला’ के कवि कौन हैं?", options: ["हरिवंश राय बच्चन", "जयशंकर प्रसाद", "महादेवी वर्मा"], answer: "हरिवंश राय बच्चन" },
  { q: "‘साकेत’ महाकाव्य के रचयिता कौन हैं?", options: ["मैथिलीशरण गुप्त", "रामधारी सिंह दिनकर", "जयशंकर प्रसाद"], answer: "मैथिलीशरण गुप्त" },
  { q: "‘रश्मिरथी’ किस कवि की रचना है?", options: ["रामधारी सिंह दिनकर", "महादेवी वर्मा", "सूरदास"], answer: "रामधारी सिंह दिनकर" },
  { q: "‘कामायनी’ किस कवि की रचना है?", options: ["जयशंकर प्रसाद", "महादेवी वर्मा", "मैथिलीशरण गुप्त"], answer: "जयशंकर प्रसाद" },
  { q: "‘यामा’ किस कवयित्री की रचना है?", options: ["महादेवी वर्मा", "सुभद्राकुमारी चौहान", "कबीर"], answer: "महादेवी वर्मा" },
  { q: "‘झाँसी की रानी’ कविता किसकी है?", options: ["सुभद्राकुमारी चौहान", "महादेवी वर्मा", "तुलसीदास"], answer: "सुभद्राकुमारी चौहान" },
  { q: "‘सूरसागर’ किसकी रचना है?", options: ["सूरदास", "कबीर", "तुलसीदास"], answer: "सूरदास" },
  { q: "‘बचपन के दिन’ किसकी आत्मकथा है?", options: ["महादेवी वर्मा", "सुभद्राकुमारी चौहान", "रामधारी सिंह दिनकर"], answer: "महादेवी वर्मा" },
  { q: "‘अंधायुग’ किसकी रचना है?", options: ["धर्मवीर भारती", "रामधारी सिंह दिनकर", "जयशंकर प्रसाद"], answer: "धर्मवीर भारती" },
  { q: "‘कबीर ग्रंथावली’ किसकी रचना है?", options: ["कबीर", "तुलसीदास", "सूरदास"], answer: "कबीर" },
  { q: "‘गीतांजलि’ का हिंदी अनुवाद किसने किया?", options: ["रवीन्द्रनाथ ठाकुर", "महादेवी वर्मा", "हरिवंश राय बच्चन"], answer: "रवीन्द्रनाथ ठाकुर" },
  { q: "‘पंचतंत्र’ की कहानियाँ किस भाषा से अनूदित हैं?", options: ["संस्कृत", "पाली", "प्राकृत"], answer: "संस्कृत" },
  { q: "‘नीलकंठ’ उपन्यास किसका है?", options: ["भारतेंदु हरिश्चंद्र", "जयशंकर प्रसाद", "मुंशी प्रेमचंद"], answer: "भारतेंदु हरिश्चंद्र" },
  { q: "‘अभिज्ञान शाकुंतलम्’ का हिंदी अनुवाद किसने किया?", options: ["कालिदास", "जयशंकर प्रसाद", "रामधारी सिंह दिनकर"], answer: "कालिदास" },
  { q: "‘भारत भारती’ किस कवि की रचना है?", options: ["मैथिलीशरण गुप्त", "रामधारी सिंह दिनकर", "जयशंकर प्रसाद"], answer: "मैथिलीशरण गुप्त" },
  { q: "‘साकेत’ किस महाकाव्य का नाम है?", options: ["रामकथा", "महाभारत", "गीता"], answer: "रामकथा" },
  { q: "‘कर्मभूमि’ उपन्यास किसका है?", options: ["मुंशी प्रेमचंद", "जयशंकर प्रसाद", "महादेवी वर्मा"], answer: "मुंशी प्रेमचंद" },
  { q: "‘निर्मला’ उपन्यास किसका है?", options: ["मुंशी प्रेमचंद", "रामधारी सिंह दिनकर", "महादेवी वर्मा"], answer: "मुंशी प्रेमचंद" },
  { q: "‘रंगभूमि’ उपन्यास किसका है?", options: ["मुंशी प्रेमचंद", "जयशंकर प्रसाद", "मैथिलीशरण गुप्त"], answer: "मुंशी प्रेमचंद" },
  { q: "‘गबन’ उपन्यास किसका है?", options: ["मुंशी प्रेमचंद", "महादेवी वर्मा", "रामधारी सिंह दिनकर"], answer: "मुंशी प्रेमचंद" },
  { q: "‘सेवासदन’ उपन्यास किसका है?", options: ["मुंशी प्रेमचंद", "जयशंकर प्रसाद", "महादेवी वर्मा"], answer: "मुंशी प्रेमचंद" },
  { q: "‘अंधायुग’ किस विषय पर आधारित है?", options: ["महाभारत", "रामायण", "गीता"], answer: "महाभारत" },
  { q: "‘साकेत’ किस महाकाव्य का नाम है?", options: ["रामकथा", "महाभारत", "गीता"], answer: "रामकथा" },
  { q: "‘गीत गोविंद’ किस कवि की रचना है?", options: ["जयदेव", "कबीर", "सूरदास"], answer: "जयदेव" },
  { q: "‘रामचरितमानस’ किस भाषा में लिखा गया?", options: ["संस्कृत", "अवधी", "ब्रज"], answer: "अवधी" },
  { q: "‘कबीर’ किस प्रकार की रचनाएँ करते थे?", options: ["दोहा", "कविता", "नाटक"], answer: "दोहा" },
  { q: "‘सुभद्राकुमारी चौहान’ किस कविता के लिए प्रसिद्ध हैं?", options: ["झाँसी की रानी", "साकेत", "कामायनी"], answer: "झाँसी की रानी" },
  { q: "‘महादेवी वर्मा’ किस युग की कवयित्री हैं?", options: ["छायावाद", "रीतिकाल", "भक्तिकाल"], answer: "छायावाद" },
  { q: "‘रामधारी सिंह दिनकर’ किस रचना के लिए प्रसिद्ध हैं?", options: ["रश्मिरथी", "कामायनी", "साकेत"], answer: "रश्मिरथी" },
  { q: "‘जयशंकर प्रसाद’ किस रचना के लिए प्रसिद्ध हैं?", options: ["कामायनी", "साकेत", "अंधायुग"], answer: "कामायनी" },
  { q: "‘भारतेंदु हरिश्चंद्र’ किस युग के कवि हैं?", options: ["आधुनिक युग", "भक्तिकाल", "रीतिकाल"], answer: "आधुनिक युग" },
  { q: "‘सूरदास’ किस भाषा में रचना करते थे?", options: ["ब्रज", "अवधी", "संस्कृत"], answer: "ब्रज" },
  { q: "‘तुलसीदास’ किस भाषा में रचना करते थे?", options: ["अवधी", "ब्रज", "संस्कृत"], answer: "अवधी" },
  { q: "‘कबीर’ किस भाषा में रचना करते थे?", options: ["अवधी", "ब्रज", "साधुकड़ी"], answer: "साधुकड़ी" },
  { q: "‘रामचरितमानस’ किस विषय पर आधारित है?", options: ["रामायण", "महाभारत", "गीता"], answer: "रामायण" },
  { q: "‘साकेत’ किस विषय पर आधारित है?", options: ["रामकथा", "महाभारत", "गीता"],
  ]
};

let currentQuestion = 0;
let subject = new URLSearchParams(window.location.search).get("subject");
let quizBox = document.getElementById("quiz-container");
let quizTitle = document.getElementById("quiz-title");

if (subject && questions[subject]) {
  quizTitle.innerText = subject + " Quiz";
  loadQuestion();
}

function loadQuestion() {
  let q = questions[subject][currentQuestion];
  quizBox.innerHTML = `
    <p>${q.q}</p>
    ${q.options.map(opt => `<button onclick="checkAnswer('${opt}')">${opt}</button>`).join("")}
  `;
}

function checkAnswer(selected) {
  let correct = questions[subject][currentQuestion].answer;
  alert(selected === correct ? "✅ Correct!" : "❌ Wrong!");
}

function nextQuestion() {
  currentQuestion++;
  if (currentQuestion < questions[subject].length) {
    loadQuestion();
  } else {
    quizBox.innerHTML = "<p>🎉 Quiz Completed! Well done.</p>";
  }
}